-- Day 14

-- 1. Customer Lifetime (in months)

WITH order_month AS (
SELECT cust_id, MIN(DATE_FORMAT(order_date, '%Y-%m')) AS first_order_month, MAX(DATE_FORMAT(order_date, '%Y-%m')) AS last_order_month
FROM orders_d14
GROUP BY cust_id
),
active_month AS (
SELECT cust_id, COUNT(DISTINCT DATE_FORMAT(order_date, '%Y-%m')) AS no_of_active_months
FROM orders_d14
WHERE `status` = 'completed'
GROUP BY cust_id
)
SELECT o.cust_id, o.first_order_month, o.last_order_month, a.no_of_active_months
FROM order_month o JOIN active_month a
ON o.cust_id = a.cust_id;

-- 2. Purchase Frequency per Customer
WITH order_count AS (
SELECT cust_id, COUNT(order_id) AS total_completed_orders, DATE_FORMAT(order_date, '%Y-%m') AS `month`
FROM orders_d14
WHERE `status` = 'completed'
GROUP BY cust_id, `month`
),
avg_orders AS(
SELECT cust_id, SUM(total_completed_orders) AS total_orders, COUNT(`month`) AS active_months
FROM order_count
GROUP BY cust_id
)
SELECT cust_id, total_orders, 
ROUND(total_orders / active_months, 2) AS avg_orders_per_active_month
FROM avg_orders;

SELECT * FROM orders_d14;

-- 3. Average Revenue per Active Month
WITH revenue_month AS (
SELECT cust_id, SUM(order_amount) AS total_revenue, COUNT(DISTINCT DATE_FORMAT(order_date, '%Y-%m')) AS active_months
FROM orders_d14
GROUP BY cust_id
)
SELECT cust_id, total_revenue, active_months, 
ROUND(total_revenue / active_months, 2) AS avg_revenue_per_active_month
FROM revenue_month;


-- 4. Revenue Quality Classification
WITH month_det AS (
SELECT cust_id,
COUNT(DISTINCT DATE_FORMAT(order_date, '%Y-%m')) AS active_months, 
SUM(order_amount) AS total_revenue
FROM orders_d14
GROUP BY cust_id
),
avg_month AS(
SELECT cust_id, active_months, ROUND(total_revenue/active_months, 2) AS avg_month_revenue
FROM month_det
)
SELECT cust_id, active_months, avg_month_revenue,
	CASE 
    WHEN active_months >= 2 AND avg_month_revenue >= 1500 THEN  'Healthy'
    WHEN active_months = 1 AND avg_month_revenue >= 2500 THEN 'At Risk'
    ELSE 'Low Value'
	END AS customer_health
FROM avg_month;

-- Business Questions

-- 1. Why is “total revenue” alone a misleading metric for customer value?

/* Other than "total revenue", need to consider other factors such as the customer is new or returning, average revenue generated monthly, 
purchase frequency, number of orders completed/cancelled, etc. */

-- 2.  Which customer is more valuable: a) ₹4,000 one-time buyer  or b) ₹1,500/month customer for 3 months   Why?

/* Customer who is spending ₹1,500/month for 3 months is more valuable as it shows repeated purchasing capability, returning customer, loyalty even though the 
short term revenue is less.  */

-- 3. If most revenue comes from At Risk customers, what problem does the business have?

/* There is a high chance of losing revenue and loss of business in long term in case of churn and it shows that there is a failure in retaining customers
and making them return */

-- 4. What would you show leadership: total revenue (or) revenue per active month. Why?

/* Revenue per active month as it gives a detailed picture of the income generated by the customers monthly and the impact it could have on the long term growth so it helps
 make the business decisions and plan accordingly */ 